# Generated by Django 2.1.8 on 2019-05-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_kind', models.CharField(max_length=20)),
                ('dog_date', models.DateTimeField(verbose_name='lost date')),
                ('body', models.TextField()),
            ],
        ),
    ]
