# Generated by Django 2.1.8 on 2019-05-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enroll',
            new_name='Dog',
        ),
    ]
