# Generated by Django 2.1.8 on 2019-05-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20190504_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
