# Generated by Django 2.1.8 on 2019-05-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_dog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
